<?php
session_start();
?>
<div id="description">
	<br/>Bonjour à tous,<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Actuellement titulaire d'un Baccalauréat Scientifique (Bac S obtenu à Hirson dans l'aisne) et d'un Diplôme Universitaire de Technologie (DUT) en Informatique (Bac+2 obtenu à Reims), je prépare une Licence Informatique (Bac+3 à Reims) afin de poursuivre sur un Master (Bac+5 à Reims). Spécialisé en Imagerie Numérique lors de la deuxième année du DUT, je compte poursuivre cette spécialité à l'aide du Master professionnel "Ingénerie de l'Image et de la Connaissance".<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Les diplômés d'un Master IIS s’insèrent dans des milieux professionnels très divers en tant qu’informaticiens ayant des compétences en imagerie. Sur le marché du travail, cette spécialisation leur permet de se différencier d’ingénieurs informaticiens généralistes en enrichissant leur offre de service. En termes de métier, le titulaire du master ayant cette spécialisation professionnelle peut : intégrer une équipe de Recherche & Développement pour y apporter des compétences en imagerie, épauler une équipe de production ou de développement par une double compétence en informatique et en imagerie, participer à des missions dont l’objectif est le choix, la mise en oeuvre ou le développement de systèmes de vision. Les secteurs économiques concernés par l’embauche de ces diplômés sont les entreprises utilisatrices des techniques en lien avec l’imagerie (en production, recherche et développement, contrôle de qualité, simulation numérique, synthèse d’images, visualisation,…), les sociétés de services et d’ingénierie informatique (SSII) et les entreprises plus spécifiques du secteur de l’imagerie. Le stage d'une durée de 4 à 6 mois permet aux jeunes diplômés de proposer leurs talents qu'ils soient intellectuels que pratiques.<br/><br/><br/><div id="CV"><a href="./docs/CV.pdf">Visionner mon Curriculum Vitae au format PDF.(A venir)</a></div><br/><br/>
</div>
<div id="zone-menu-bas">
	<a href="index.php?nom=accueil" id="accueil2">Accueil</a> :: <a href="index.php?nom=private.inc" id="private">Private</a>
</div>
